/**
 * Export Utilities for Analysis Results
 * Supports Markdown and PDF export formats
 */

/**
 * Generate Markdown report from analysis data
 */
export const generateMarkdownReport = (project, analysis) => {
  const timestamp = new Date().toLocaleString()
  const summary = analysis.summary || {}
  const files = analysis.files || []
  
  let markdown = `# Code Analysis Report\n\n`
  markdown += `**Project:** ${project.name}\n`
  markdown += `**Repository:** ${project.github_url}\n`
  markdown += `**Generated:** ${timestamp}\n\n`
  
  markdown += `---\n\n`
  
  // Summary Section
  markdown += `## Summary\n\n`
  markdown += `| Metric | Value |\n`
  markdown += `|--------|-------|\n`
  markdown += `| Total Files | ${summary.total_files || 0} |\n`
  markdown += `| Lines of Code | ${(summary.total_lloc || summary.total_sloc || summary.loc || 0).toLocaleString()} |\n`
  markdown += `| Functions | ${summary.total_functions || 0} |\n`
  markdown += `| Classes | ${summary.total_classes || 0} |\n\n`
  
  // Language Distribution
  if (summary.languages && Object.keys(summary.languages).length > 0) {
    markdown += `## Language Distribution\n\n`
    markdown += `| Language | Files |\n`
    markdown += `|----------|-------|\n`
    
    Object.entries(summary.languages).forEach(([language, count]) => {
      const fileCount = typeof count === 'number' ? count : (count?.count || 0)
      markdown += `| ${language} | ${fileCount} |\n`
    })
    markdown += `\n`
  }
  
  // Complexity Analysis
  markdown += `## Complexity Analysis\n\n`
  const complexityDist = calculateComplexityDistribution(files)
  if (complexityDist) {
    markdown += `| Complexity Level | Files | Percentage |\n`
    markdown += `|-----------------|-------|------------|\n`
    markdown += `| Low (1-5) | ${complexityDist.low} | ${complexityDist.lowPercent}% |\n`
    markdown += `| Medium (6-10) | ${complexityDist.medium} | ${complexityDist.mediumPercent}% |\n`
    markdown += `| High (11-20) | ${complexityDist.high} | ${complexityDist.highPercent}% |\n`
    markdown += `| Very High (20+) | ${complexityDist.veryHigh} | ${complexityDist.veryHighPercent}% |\n\n`
    
    markdown += `**Maintainable Files:** ${complexityDist.low + complexityDist.medium}\n`
    markdown += `**Files Needing Review:** ${complexityDist.high + complexityDist.veryHigh}\n\n`
  }
  
  // File Details
  markdown += `## File Details\n\n`
  markdown += `| File | Lines | Complexity | Functions | Classes |\n`
  markdown += `|------|-------|------------|-----------|----------|\n`
  
  files.slice(0, 50).forEach(file => {
    const fileName = (file.file_path || file.path || 'Unknown').split('/').pop()
    const lines = file.metrics?.raw?.loc || file.lines || 0
    const complexity = file.metrics?.complexity?.cyclomatic || 0
    const functions = file.metrics?.functions || 0
    const classes = file.metrics?.classes || 0
    
    markdown += `| ${fileName} | ${lines} | ${complexity} | ${functions} | ${classes} |\n`
  })
  
  if (files.length > 50) {
    markdown += `\n*Showing first 50 files. Total: ${files.length} files*\n`
  }
  
  markdown += `\n---\n\n`
  markdown += `*Generated by CodeCompass - AI-Powered Code Analysis Tool*\n`
  
  return markdown
}

/**
 * Calculate complexity distribution from files
 */
const calculateComplexityDistribution = (files) => {
  if (!files || files.length === 0) return null
  
  const dist = { low: 0, medium: 0, high: 0, veryHigh: 0 }
  
  files.forEach(file => {
    const complexity = file.metrics?.complexity?.cyclomatic || 0
    if (complexity <= 5) dist.low++
    else if (complexity <= 10) dist.medium++
    else if (complexity <= 20) dist.high++
    else dist.veryHigh++
  })
  
  const total = files.length
  return {
    ...dist,
    lowPercent: ((dist.low / total) * 100).toFixed(1),
    mediumPercent: ((dist.medium / total) * 100).toFixed(1),
    highPercent: ((dist.high / total) * 100).toFixed(1),
    veryHighPercent: ((dist.veryHigh / total) * 100).toFixed(1)
  }
}

/**
 * Download file to user's computer
 */
export const downloadFile = (content, filename, mimeType) => {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Export analysis as Markdown file
 */
export const exportAsMarkdown = (project, analysis) => {
  const markdown = generateMarkdownReport(project, analysis)
  const filename = `${project.name.replace(/\s+/g, '_')}_analysis_${Date.now()}.md`
  downloadFile(markdown, filename, 'text/markdown')
}

/**
 * Export analysis as JSON file
 */
export const exportAsJSON = (project, analysis) => {
  const data = {
    project: {
      name: project.name,
      github_url: project.github_url,
      description: project.description
    },
    analysis: analysis,
    exported_at: new Date().toISOString()
  }
  
  const json = JSON.stringify(data, null, 2)
  const filename = `${project.name.replace(/\s+/g, '_')}_analysis_${Date.now()}.json`
  downloadFile(json, filename, 'application/json')
}

/**
 * Generate HTML report (can be printed as PDF)
 */
export const generateHTMLReport = (project, analysis) => {
  const markdown = generateMarkdownReport(project, analysis)
  
  // Convert markdown to HTML (basic conversion)
  let html = markdown
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^\*\*(.*)\*\*/gim, '<strong>$1</strong>')
    .replace(/^\*(.*)\*/gim, '<em>$1</em>')
    .replace(/^---$/gim, '<hr>')
    .replace(/\n/g, '<br>')
  
  const fullHTML = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${project.name} - Analysis Report</title>
  <style>
    body {
      font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 40px 20px;
      line-height: 1.6;
      color: #161616;
    }
    h1 { color: #0f62fe; border-bottom: 3px solid #0f62fe; padding-bottom: 10px; }
    h2 { color: #161616; margin-top: 30px; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }
    h3 { color: #525252; }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #e0e0e0;
    }
    th {
      background: #f4f4f4;
      font-weight: 600;
      color: #161616;
    }
    tr:hover { background: #f4f4f4; }
    hr { border: none; border-top: 2px solid #e0e0e0; margin: 30px 0; }
    strong { color: #0f62fe; }
    @media print {
      body { padding: 20px; }
      h1 { page-break-before: avoid; }
    }
  </style>
</head>
<body>
  ${html}
</body>
</html>
  `
  
  return fullHTML
}

/**
 * Export analysis as HTML (printable as PDF)
 */
export const exportAsHTML = (project, analysis) => {
  const html = generateHTMLReport(project, analysis)
  const filename = `${project.name.replace(/\s+/g, '_')}_analysis_${Date.now()}.html`
  downloadFile(html, filename, 'text/html')
}

/**
 * Print report (opens print dialog)
 */
export const printReport = (project, analysis) => {
  const html = generateHTMLReport(project, analysis)
  const printWindow = window.open('', '_blank')
  printWindow.document.write(html)
  printWindow.document.close()
  printWindow.focus()
  setTimeout(() => {
    printWindow.print()
  }, 250)
}

// Made with Bob
